// Generated by https://quicktype.io

// JSON data datatypes
export interface SamplesData {
    samples: Sample[];
}

export interface Sample {
    _id:          string;
    name:        string;
    description: string;
    url:         string;
    images:      Image[];
    technologies: string[];
}

export interface Image {
    filename: string;
}